image: docker:19.03.1
  
services:
  - docker:19.03.1-dind
  
stages:
  - build
  - deploy
  - tag

BuildProd:
  stage: build
  tags:
    - api
  only:
    - master
  script:
    - docker build --no-cache -t ${SYSTEM_NAME}-api .
    
DeployProd:
  stage: deploy
  tags:
    - api
  only:
    - master
  script:
    - docker stack deploy -c docker-compose.yml ${SYSTEM_NAME}
#    - docker service update --force --image ${SYSTEM_NAME}-api:latest ${SYSTEM_NAME}_api

semantic_release:
  stage: tag
  tags:
    - api
  image: node:latest
  tags:
    - docker
  variables:
    GITLAB_TOKEN: $TOKEN_GITLAB
    GITLAB_URL: $URL_GITLAB
  before_script:
    - npm install semantic-release @semantic-release/gitlab -D
  script:
    - npm run semantic-release
  only:
    - master