version: "3.4"

services:
  api:
    image: myhome-api:latest
    networks:
      - traefik-public
    deploy:
      update_config:
        order: start-first
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.apimyhome.rule=Host(`api.well.eti.br`) && PathPrefix(`/myhome`)"
      - "traefik.http.routers.apimyhome.entrypoints=web"
      - "traefik.http.routers.apimyhome.tls=true"
      - "traefik.http.routers.apimyhome.tls.certresolver=default"
      - "traefik.http.services.apimyhome.loadbalancer.server.port=3000"
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASS=${MARIADB_PASS}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DB=${MARIADB_DB}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DB=${MONGODB_DB}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - PORT_API=${PORT_API}
      - ONESIGNAL_API_ID=${ONESIGNAL_API_ID}
      - ONESIGNAL_TOKEN=${ONESIGNAL_TOKEN}
      - ONESIGNAL_PORT=${ONESIGNAL_PORT}
      - ONESIGNAL_HOST=${ONESIGNAL_HOST}
      - ONESIGNAL_PATH=${ONESIGNAL_PATH}
      - SMTP_SERVER=#{SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - BASE_PATH=${BASE_PATH}
networks:
  traefik-public:
    external: true    
